version: '2'

services: 
   makeen:
      image: makeenllc/makeen-core:${MAKEEN_DOCKER_TAG}
      environment:
         - MAKEEN_ENV_SERVER_CACHE_URI=mongodb://mongo:27017
         - MAKEEN_ENV_REGISTRATIONS_1_PLUGIN_OPTIONS_MONGODB_HOST=mongo
      depends_on:
         - mongo
      links:
         - mongo
      ports:
         - "3000:3003"
      labels:
         kompose.service.type: LoadBalancer
   mongo:
      image: mongo:3.4